import Head from 'next/head'

import { Header } from '@/components/header/Header'
import { TaskCards } from '@/components/task/TaskCards'
import styles from '@/styles/Home.module.css'

import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TaskCards />
    </div>
  )
}

export default Home
